#!/usr/bin/python3
#

try:
	print(r)
	fuxk
	# Exception as e can catch all the errro
except Exception as e:
	print(e)
else:
	print('ok')
finally:
	print('catch over')